const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const grid=$("#grid"),cats=$("#cats"),search=$("#search"),sort=$("#sort");
const motoDialog=$("#motoDialog"),paymentDialog=$("#paymentDialog"),agencyDialog=$("#agencyDialog"),calcDialog=$("#calcDialog");
let active="Todas",selectedMoto=null,exactCalc=0,roundedCalc=0,paymentType="",selectedBank="",selectedInstallments="",creditDownPayment=0;
const q=n=>"Q"+Number(n||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});
const roundUp=(n,step=100)=>Math.ceil(Number(n||0)/step)*step;
function paths(n){const v=[n,String(n).toLowerCase(),String(n).toUpperCase()];const e=["webp","png","jpg","jpeg","WEBP","PNG","JPG","JPEG"];const f=["assets/img/motos","assets/img"];let a=[];f.forEach(x=>[...new Set(v)].forEach(y=>e.forEach(z=>a.push(`${x}/${y}.${z}`))));return a}
function img(el,name,alt){let p=paths(name),i=0;el.alt=alt||name;el.onerror=()=>{i++; if(i<p.length)el.src=p[i]; else{el.onerror=null;let d=document.createElement("div");d.className="no-img";d.textContent=alt||name;el.replaceWith(d)}};el.src=p[0]}
function priceHtml(m){return `${m.oldPrice?`<span class="oldPrice">${q(m.oldPrice)}</span>`:""}<span>${q(m.precio)}</span>${m.oldPrice?`<span class="discountTag">Oferta</span>`:""}`}
function buildCats(){let c={Todas:motos.length};motos.forEach(m=>c[m.categoria]=(c[m.categoria]||0)+1);cats.innerHTML=Object.entries(c).map(([k,v])=>`<button class="cat ${k==active?"active":""}" data-cat="${k}">${k} · ${v}</button>`).join("");$$(".cat").forEach(b=>b.onclick=()=>{active=b.dataset.cat;buildCats();render()})}
function list(){let s=search.value.toLowerCase().trim();let l=motos.filter(m=>(active=="Todas"||m.categoria==active)&&`${m.nombre} ${m.detalle} ${m.categoria} ${m.sku} ${m.codigo}`.toLowerCase().includes(s));if(sort.value=="priceAsc")l.sort((a,b)=>a.precio-b.precio);if(sort.value=="priceDesc")l.sort((a,b)=>b.precio-a.precio);if(sort.value=="nameAsc")l.sort((a,b)=>a.nombre.localeCompare(b.nombre));return l}
function render(){grid.innerHTML="";list().forEach(m=>{let c=document.createElement("article");c.className="card";c.innerHTML=`<span class="tag">${m.categoria}</span><div class="photo"><img loading="lazy"></div><h3>${m.nombre}</h3><p class="detail">${m.detalle}</p><div class="price">${priceHtml(m)}</div><button class="interest">Me interesa esto</button>`;img(c.querySelector("img"),m.img,m.nombre);c.onclick=()=>openMoto(m);c.querySelector(".interest").onclick=e=>{e.stopPropagation();selectedMoto=m;openPayment()};grid.appendChild(c)})}
function openMoto(m){selectedMoto=m;$("#modalCat").textContent=m.categoria;$("#modalName").textContent=m.nombre;$("#modalDetail").textContent=m.detalle;$("#modalPrice").textContent=q(m.precio);$("#modalOldWrap").innerHTML=m.oldPrice?`<span class="oldModal">${q(m.oldPrice)}</span> <span class="discountTag">Oferta</span>`:"";$("#modalSku").textContent=m.sku;$("#modalCode").textContent=m.codigo;let old=$("#modalImg"),clone=old.cloneNode();old.replaceWith(clone);img(clone,m.img,m.nombre);motoDialog.showModal()}
function resetPayment(){paymentType="";selectedBank="";selectedInstallments="";creditDownPayment=0;$("#paymentOptions").classList.remove("hidden");$("#creditStep").classList.add("hidden");$("#visaBankStep").classList.add("hidden");$("#visaInstallmentStep").classList.add("hidden")}
function paymentLabel(){return paymentType==="credito"?"crédito":paymentType==="visa"?"visa cuotas":paymentType==="contado"?"contado":"información"}
function openPayment(){if(!selectedMoto)return;resetPayment();$("#paymentMotoText").textContent=`Moto seleccionada: ${selectedMoto.nombre} - ${selectedMoto.detalle}`;paymentDialog.showModal()}
function openAgency(){ $("#agencyText").textContent=selectedMoto?`Consulta por ${selectedMoto.nombre} - ${selectedMoto.detalle} · Pago: ${paymentLabel()}`:"Te enviaremos a WhatsApp."; agencyDialog.showModal()}
function wa(key,custom){let a=agencias[key];let msg=custom;if(!msg){if(selectedMoto){msg=`Hola, me interesa ${selectedMoto.nombre} (${selectedMoto.detalle}). Me interesa tipo de pago: ${paymentLabel()}. Precio de contado: ${q(selectedMoto.precio)}.`;if(paymentType==="credito"){msg+=` Mínimo de enganche redondeado: ${q(creditDownPayment)}. Nota: si el enganche es mayor, el interés es menor.`}if(paymentType==="visa"){msg+=` Banco de tarjeta: ${selectedBank}. Tiempo de pago: ${selectedInstallments} cuotas. Nota: algunos bancos cobran un porcentaje por el pago que puede ir del 2.38% al 6.25% dependiendo del banco.`}if(paymentType==="contado"){msg+=` Deseo recibir información para compra de contado.`}msg+=` Quiero comunicarme con agencia ${a.nombre}.`}else{msg=`Hola, quiero información del catálogo de motocicletas. Quiero comunicarme con agencia ${a.nombre}.`}}open(`https://wa.me/${a.telefono}?text=${encodeURIComponent(msg)}`,"_blank")}
function calc(){let v=Number($("#calcValue").value||0);exactCalc=v*.15;roundedCalc=roundUp(exactCalc,100);$("#calcExact").textContent=q(exactCalc);$("#calcResult").textContent=q(roundedCalc)}
search.oninput=render;sort.onchange=render;$("#contactBtn").onclick=()=>{selectedMoto=null;openAgency()};$("#calcBtn").onclick=()=>calcDialog.showModal();$("#interestBtn").onclick=openPayment;$("#calcValue").oninput=calc;
$$("[data-close]").forEach(b=>b.onclick=()=>motoDialog.close());$$("[data-close-payment]").forEach(b=>b.onclick=()=>paymentDialog.close());$$("[data-close-agency]").forEach(b=>b.onclick=()=>agencyDialog.close());$$("[data-close-calc]").forEach(b=>b.onclick=()=>calcDialog.close());
$$("[data-agency]").forEach(b=>b.onclick=()=>wa(b.dataset.agency));$$("[data-calc-agency]").forEach(b=>b.onclick=()=>{let val=Number($("#calcValue").value||0);let a=agencias[b.dataset.calcAgency];wa(b.dataset.calcAgency,`Hola, calculé un enganche para una moto con valor de ${q(val)}. El 15% es ${q(exactCalc)} y el mínimo de enganche redondeado es ${q(roundedCalc)}. Deseo comunicarme con agencia ${a.nombre}.`)});
$$("[data-pay]").forEach(b=>b.onclick=()=>{paymentType=b.dataset.pay;if(paymentType==="contado"){paymentDialog.close();openAgency()}if(paymentType==="credito"){creditDownPayment=roundUp(selectedMoto.precio*.15,100);$("#creditDownPayment").textContent=q(creditDownPayment);$("#paymentOptions").classList.add("hidden");$("#creditStep").classList.remove("hidden")}if(paymentType==="visa"){$("#paymentOptions").classList.add("hidden");$("#visaBankStep").classList.remove("hidden")}})
$("#creditNext").onclick=()=>{paymentDialog.close();openAgency()}
const banks=["BI","Proamérica","G&T","BAM","Bantrab","Occidente","Banrural","Ficohsa","Micoope","Otros"];$("#bankGrid").innerHTML=banks.map(b=>`<button class="bankBtn" data-bank="${b}">${b}</button>`).join("");$$("[data-bank]").forEach(b=>b.onclick=()=>{selectedBank=b.dataset.bank;$("#visaBankStep").classList.add("hidden");$("#visaInstallmentStep").classList.remove("hidden")});
const months=[6,10,12,15,18];$("#installmentGrid").innerHTML=months.map(m=>`<button class="bankBtn" data-months="${m}">${m} cuotas</button>`).join("");$$("[data-months]").forEach(b=>b.onclick=()=>{selectedInstallments=b.dataset.months;paymentDialog.close();openAgency()});
const heroLogo=$("#heroLogo"),logoList=["assets/img/logo-malacatan.png","assets/img/logo-sanpablo.png"];let logoIndex=0;setInterval(()=>{logoIndex=(logoIndex+1)%logoList.length;heroLogo.classList.remove("logoFade");void heroLogo.offsetWidth;heroLogo.src=logoList[logoIndex];heroLogo.classList.add("logoFade")},6500);
buildCats();render();
